_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

#min_epochs: 1 # prevents early stopping
#max_steps: 1000000
#max_time: 00:12:00:00
max_steps: 40

accelerator: gpu
devices: 1

# mixed precision for extra speed-up
# precision: 16

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False
