_target_: src.models.brats_module.BraTSLitModule
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0005
  betas: [0.9, 0.999]
  eps: 1e-7
  weight_decay: 0.001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.networks.nnunet.PlainConvUNet
  input_channels: 4
  n_stages: 6
  features_per_stage: [32, 64, 125, 256, 320, 320]
  conv_op: 
    _target_: hydra.utils.get_class
    path: torch.nn.Conv3d
  kernel_sizes: 3
  strides: [1, 2, 2, 2, 2, 2]
  n_conv_per_stage: [2, 2, 2, 2, 2, 2]
  num_classes: 6
  n_conv_per_stage_decoder: [2, 2, 2, 2, 2]
  conv_bias: False
  norm_op: 
    _target_: hydra.utils.get_class
    path: torch.nn.BatchNorm3d
  norm_op_kwargs: null
  dropout_op: null
  dropout_op_kwargs: null
  nonlin: 
    _target_: hydra.utils.get_class
    path: torch.nn.ReLU
  nonlin_kwargs: null
  deep_supervision: False
  nonlin_first: False

inferer:
  _target_: monai.inferers.SlidingWindowInferer
  roi_size: ${data.roi_size}
  sw_batch_size: 1
  overlap: 0.25

