_target_: src.models.patch_tumor_pred_diffusion_module_simpl_new_no_consistencyloss.PatchTumorDiffusionLitModule
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4
  weight_decay: 1e-3

scheduler:
  _target_: src.scheduler.lr_scheduler.LinearWarmupCosineAnnealingLR
  _partial_: true
  warmup_epochs: 30
  max_epochs: ${trainer.max_epochs}

denoise_net:
  _target_: src.models.networks.unet.basic_unet_denoise.PatchDenoiseUNet
  spatial_dims: 3
  in_channels: ${eval:'${data.num_targets} + ${data.num_modalities}'}
  out_channels: ${data.num_targets}
  features: [64, 64, 128, 256, 512, 64]
  act: LeakyReLU
  norm: instance
  dropout: 0.0
  upsample: deconv

patchify_net:
  _target_: src.models.networks.swinunetr.swinunetr_enc.SwinUNETREnc
  img_size: ${data.roi_size}
  in_channels: ${data.num_modalities}
  out_channels: 1
  depths: [2, 4, 2, 2]
  num_heads: [3, 6, 12, 24]
  feature_size: 24
  norm_name: 'instance'
  drop_rate: 0.0
  attn_drop_rate: 0.0
  dropout_path_rate: 0.0
  normalize: True
  use_checkpoint: False
  spatial_dims: 3
  downsample: 'merging'
  use_v2: False

patch_emb_net:
  _target_: src.models.networks.unet.basic_unet.PatchUNetEncoder
  spatial_dims: 3
  in_channels: 1
  out_channels: ${data.num_modalities}
  features: [64, 64, 128, 256, 512, 64]
  act: LeakyReLU
  norm: instance
  bias: True
  dropout: 0.0
  upsample: deconv

sampler:
  _target_: src.models.diffusion.timestep_sampler.UniformSampler
  diffusion_steps: ${model.diffusion.steps}


diffusion:
  _target_: src.models.diffusion.build_diffusion.BuildDiffusion
  steps: 1000
  sample_steps: 10
  noise_schedule: linear
  model_mean_type: START_X
  model_var_type: FIXED_LARGE
  loss_type: MSE

inferer:
  _target_: monai.inferers.SlidingWindowInferer
  roi_size: ${data.roi_size}
  sw_batch_size: 2
  overlap: 0.25

extra_kwargs:
  num_targets: ${data.num_targets}
  roi_size: ${data.roi_size}
  sampling_type: ddim_sample_uncer_aware
  uncer_step: 4
  patch_sizes: ${data.patch_sizes}
  patch_emb_size: 8
  microbatch: -1
  patch_thresh: 0.70
  subregions_names: ['WT', 'TC', 'ET']


# compile model for faster training with pytorch 2.0
compile: false