_target_: src.models.brats_module.BraTSLitModule
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.networks.swinunetr.SwinUNETR
  img_size: ${data.roi_size}
  in_channels: 4
  out_channels: 3
  depths: [2, 4, 2, 2]
  num_heads: [3, 6, 12, 24]
  feature_size: 24
  norm_name: 'instance'
  drop_rate: 0.0
  attn_drop_rate: 0.0
  dropout_path_rate: 0.0
  normalize: True
  use_checkpoint: False
  spatial_dims: 3
  downsample: 'merging'
  use_v2: False

inferer:
  _target_: monai.inferers.SlidingWindowInferer
  roi_size: ${data.roi_size}
  sw_batch_size: 1
  overlap: 0.25