defaults:
  - model_save_callback
  - model_summary
  - rich_progress_bar
  - _self_

model_save_callback:
  save_dir: ${paths.output_dir}/checkpoints
  save_interval: 10000


early_stopping:
  monitor: "train/loss"
  patience: 100
  mode: "min"

model_summary:
  max_depth: -1
