defaults:
  - model_save_callback
  - model_checkpoint
  - model_summary
  - rich_progress_bar
  - _self_


#model_save_callback:
#  save_dir: ${paths.output_dir}/checkpoints
#  save_interval: 20000

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: 'model_{global_step}'
  monitor: 'global_step'
  mode: 'max'
  every_n_train_steps: 10
  verbose: True
  every_n_epochs: 0
  save_top_k: 1



model_summary:
  max_depth: -1
