synapse_submission:
  _target_: src.callbacks.synapse_submission_callback.SynapseSubmissionCallBack
  auth_file: ${synapse.auth_file}
  syn_proj_id: ${synapse.syn_proj_id}
  pred_labels_path: ${hydra:runtime.output_dir}/seg_masks
  eval_images_path: ${data.data_dir}/test
  syn_eval_id: '9615339'
  zip_file_name: ${task_tag}_${now:%Y-%m-%d}_${now:%H-%M-%S}
  name: ${.zip_file_name}