# @package _global_

defaults:
  - _self_
  - data: noise_sample_cifar
  - model: diffusion_cifar
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
#ckpt_path: "/home/sanyal/DATA/models/guided-diff-wts/64x64_diffusion.pt"
ckpt_path: "/home/sanyal/DATA/diffusion-lightning-hydra-out/logs/train/runs/2024-05-20_17-33-02/checkpoints/model_global_step=40.0.ckpt"

extra_cfg:
  clip_denoised: True

  num_samples: ${data.num_samples}

  batch_size: ${data.batch_size}

  use_ddim: False

  eta: null

  log_interval: 100


  output_dir: ${hydra:runtime.output_dir}
